### ISSUE TITLE
When the idy is integer it is not detected as idy

### ISSUE THREAD

**Issue by burgalon** [wbotelhos/idy#1]
#Sometimes hashids returns a hash which looks like an integer, and so the find function thinks it's a regular id resulting in a false 404

**Comment by wbotelhos** [comment]
Hi @burgalon ,

Could you provide me the class name and the id that generates the "fake" number id?
Are you using `find` or `findy`?

**Comment by corona6** [comment]
When `Hashids` encode like `80` (non alphabet id) it seems to get error.
https://github.com/wbotelhos/idy/blob/4deb728fb5aa59c74f9a488da6a59ad73e4241ca/lib/idy/extension.rb#L27

**Comment by wbotelhos** [comment]
I got an example just now: `Invoice.new(id: 1).idy`

I'll check it. (:

**Comment by wbotelhos** [comment]
@burgalon and @corona6 ,

The `find` method can search via string like this: `Invoice.find '1'`, so it looks like impossible say if `'1'` was generated by `idy` or by other code, so the best thing to do here is deprecated the overrided `find` method e use just the `findy` to make sure it will search via Idy.

`Invoice.findy Invoice.last.idy` solves the problem.
